### ISSUE TITLE
Can't be installed

### ISSUE THREAD

**Issue by hansolocambo** [ashvin-bhuttoo/RarbgAdvancedSearch#15] opened 2021-11-01 13:04 UTC
Setup.exe                             ->   "An error occured attempting to install [...]"
RarbgAdvancedSearch.msi   ->   "There is a problem with the Windows Installer Package [...]"

:/

**Comment by ashvin-bhuttoo** [comment] 2021-11-03 16:39
Can you please download the NSIS version of the installer and try to install with that:

https://github.com/ashvin-bhuttoo/RarbgAdvancedSearch/releases/tag/1.1.0

![image](https://user-images.githubusercontent.com/17810392/122000988-b0e2ca80-cdc0-11eb-8f3e-f8a22646aa38.png)

**Comment by ashvin-bhuttoo** [comment] 2021-11-03 16:40
duplicate of #11

**Closed as completed by ashvin-bhuttoo** 2021-11-03 16:40 UTC
